version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: ms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: msdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: