# Test Configuration
spring:
  profiles:
    active: test

  # H2 In-Memory Database for Testing
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA/Hibernate for Testing
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false

  # Disable data initialization for tests
  sql:
    init:
      mode: never

  # Disable Flyway for tests (we use create-drop)
  flyway:
    enabled: false

  # H2 Console (if needed for debugging tests)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Disable security for some tests (when needed)
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT for Testing
jwt:
  secret: TestSecretKeyThatIsLongEnoughForTestingPurposesAndMeetsTheMinimumRequirements
  expiration: 3600000

# Logging for Tests
logging:
  level:
    org.springframework: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    core.ms: DEBUG