spring:
  application:
    name: trading-system

  # Force H2 configuration
  datasource:
    url: jdbc:h2:mem:tradingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # Explicitly disable any auto-configuration that might interfere
    platform: h2
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database: H2  # Explicitly set to H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # Force H2 dialect

  # Disable DevTools datasource if present
  devtools:
    add-properties: false

  # WebSocket Configuration
  websocket:
    broker:
      enabled: true

  # Disable Flyway
  flyway:
    enabled: false

# JWT Configuration
jwt:
  secret: defaultSecretKeyThatShouldBeVeryLongAndSecureForProduction
  expiration: 86400000

# Order Book Configuration
orderbook:
  persistence:
    type: in-memory
  snapshot:
    enabled: true
    interval: 300000
    retention-days: 7

# Logging
logging:
  level:
    root: INFO
    core.ms: DEBUG
    org.hibernate.SQL: WARN

# Server
server:
  port: 8080